sup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('tinymce/', include('tinymce.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)),] 

main/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.db.models import F

from tinymce.models import HTMLField
from ckeditor.fields import RichTextField
# Create your models here.
import datetime
CATEGORY_CHOICES=[
    ('IN', 'Intrusion'),
    ('IC', 'Incendie Conventionnelle'),
    ('IA', 'Incendie Adressable'),
    ('C4', 'Câble & Energie'),
    ('C5', 'Categorie Y'),
    ]
class Marque(models.Model):
    name = models.CharField(max_length=100, verbose_name=("Nom de la marque"), blank=True, null=True)
    logo = models.ImageField(verbose_name='Logo de la marque', upload_to='produits/', blank=True, null=True)

    def __str__(self):
        return self.name
class Produit(models.Model):
    ordre           = models.IntegerField(blank=True, null=True )
    marque          = models.ForeignKey(Marque, on_delete=models.CASCADE, blank=True, null=True)
    designation     = models.CharField( max_length=150, verbose_name=("Désignation"))
    slug            = models.SlugField( max_length=70)
    category        = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default='IN')
    reference       = models.CharField(max_length=100, verbose_name=("Référence"), blank= True)
    # description     = RichTextField(verbose_name='Text en plus', blank= True, null=True)
    description_2   = HTMLField(verbose_name='partie 1', blank= True, null=True)
    description_1   = HTMLField(verbose_name='partie 2', blank= True, null=True)
    # info_sup        = RichTextField(verbose_name='informations suplaimentaires', blank= True, null=True)
    photo           = models.ImageField(verbose_name='Photo du produit', upload_to='produits/')
    fichier_1       = models.FileField(verbose_name='Fiche technique ', upload_to='fichiers/', blank= True)
    fichier_2       = models.FileField(verbose_name='Manuel instalateur', upload_to='fichiers/', blank= True)
    fichier_3       = models.FileField(verbose_name='Manuel utilisateur', upload_to='fichiers/', blank= True)
    fichier_4       = models.FileField(verbose_name='certificat', upload_to='fichiers/', blank= True)
    is_active       = models.BooleanField(verbose_name='activer', default=True)


    def __str__(self):
        return self.designation

    class Meta:
        ordering = [F('ordre').asc(nulls_last=True)]
        verbose_name = 'Produits'
        verbose_name_plural = 'Produits'



class Slide(models.Model):
    title = models.CharField(verbose_name='titre' ,max_length= 200, blank = True)
    image = models.ImageField(upload_to= 'slides/')
    class Meta:
        verbose_name = "Photo page d'accueil"
        verbose_name_plural = "Photos page d'accueil"



DEPARTEMENT_CHOICES=[
    ('C', 'Commercial'),
    ('D', 'Direction'),
    ('M', 'Marketing'),
    ('SC', 'Service client'),
    ]

class ContactForm(models.Model):
    name        = models.CharField(max_length=50)
    departement = models.CharField(max_length=2, choices=DEPARTEMENT_CHOICES, default='D',)
    email       = models.EmailField()
    phone       = models.CharField(max_length=20)
    subject     = models.CharField(max_length=50)
    fichier     = models.FileField(upload_to='fichiers/% d/% m/% Y/', max_length=20, blank=True)
    message     = models.TextField(blank=True)
    date_added  = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Formulaire de contact'

class Tag(models.Model):
    tag = models.CharField(max_length=50, verbose_name='categorie')
    def __str__(self):
        return self.tag
    class Meta:
        verbose_name = 'Categories des articles'



class Post(models.Model):
    titre = models.CharField(max_length=200)
    tag = models.ForeignKey(Tag, verbose_name='Categorie' ,on_delete=models.CASCADE, blank=True, null=True)
    slug = models.SlugField(max_length=100)
    intro = models.TextField( blank=True)
    image_1 = models.ImageField(verbose_name='Image 1' ,upload_to='slides/', blank= True, null=True)
    text_1 = HTMLField(verbose_name='text 1', blank= True, null=True)
    image_2 = models.ImageField(verbose_name='Image' ,upload_to='slides/', blank= True, null=True)
    text_2 = HTMLField(verbose_name='text 2', blank= True, null=True)
    image_3 = models.ImageField(verbose_name='Image' ,upload_to='slides/', blank= True, null=True)
    text_3 = HTMLField(verbose_name='text 3', blank= True, null=True)
    created_date = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.titre

class Catalogue(models.Model):
    nom     = models.CharField(max_length=150)
    fichier = models.FileField(upload_to='catalogues', max_length=180)

    def __str__(self):
        return self.nom

templates/_messages.html
{% if messages %}

    {% for message in messages %}
        <div id="message" class="container">

            <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
                <strong>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        Error
                        {% else %}

                    {% endif %}
                </strong>
                {{ message }}
            </div>
        </div>      
    {% endfor %}
  
{% endif %}

templates/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text text-center">
                        <!-- <h3>SUPELECTROTECH</h3> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->



    <!-- about wrap  -->
    <div class="about_wrap_area about_wrap_area2">
        <div class="container">
            <div class="row">
                <div class="col-xl-4 col-md-6 col-lg-4">
                    <div class="single_service_wrap text-center">
                        <img src="{% static 'img/svg_icon/puzzle.svg' %}" alt="">
                        <h3>Bon prix, Bon Choix</h3>
                    </div>
                </div>
                <div class="col-xl-4 col-md-6 col-lg-4">
                    <div class="single_service_wrap text-center">
                        <img src="{% static 'img/svg_icon/controls.svg' %}" alt="">
                        <h3>Qualité Garantie</h3>
                    </div>
                </div>
                <div class="col-xl-4 col-md-6 col-lg-4">
                    <div class="single_service_wrap text-center">
                        <img src="{% static 'img/svg_icon/bar-chart.svg' %}" alt="">
                        <h3>Accompagnement de A à Z</h3>
                    </div>
                </div>
              
            </div>
        </div>
    </div>
    <!--/ about wrap  -->





<!-- about  -->
<div id="suite_about" class="about_area">
    <div class="container-fluid p-0">
        <h1 class="text-center mb-5" style="color: #233774;">SUPELECTROTECH, Toujours en Bonne Voie</h1>
        <div class="row no-gutters align-items-center">
            <div class="col-xl-6 col-lg-6">
                <div class="about_image">
                    <img src="{% static 'img/about/about.png' %}" alt="">
                </div>
            </div>
            <div class="col-xl-6 col-lg-6">
                <div class="about_info">
                    <p>Fondée en 1993 et implantée à BLIDA, plus exactement à la Zone Industrielle ATLAS. <br> <strong>SUPELECTROTECH</strong> n’est pas uniquement une entreprise d’Importation, et de Distribution des équipements de sécurité électronique.</p>
                    <ul>
                        <li> Détection Intrusion </li>
                        <li> Détection Incendie conventionnelle </li>
                        <li> Détection Incendie adressable</li>
                    </ul>
                    <p>Mais aussi D’Installation et de Fabrication, qui est le fruit d’une maitrise parfaite des systèmes de sécurité électronique. <br> c'est ce qui la permis de fabriquer des parties importantes de ces systèmes sans recourir à l’importation.</p>
                
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ about  -->

    <!-- financial_solution -->
    <div class="financial_solution_area">
        <div class="container"style="padding-left:0px!important;">
            <div class="row">
                <div class="col-xl-6 col-lg-6 pt-5">
                    <div class="about_info">
                        <p> <strong class="font-weight-bold"> La Force de SUPELECTROTECH </strong> , Se mesure par sa capacité à accompagner le client et d’y répondre à ses besoins par des solutions rentables et adaptées.</p>

                        <p class="mt-3"> <strong class="font-weight-bold"> Les Engagements de SUPELECTROTECH </strong></p>
                        <ul>
                            <li class="ml-1"> <p> Professionnalisme et qualité du matériel commercialisé. </p></li>
                            <li class="ml-1"> <p> Compétitivité des prix. </p></li>
                            <li class="ml-1"> <p> Service Après Vente efficace et performant.</p></li>
                        </ul>
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6">
                    <div class="finance_thumb">
                        <img src="{% static 'img/about/finance.png' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ financial_solution -->




    <!-- counter  -->
    <center><h2 class="portfolio_details_content text-center text-uppercase mb-50" style="color: #233774;">Quelques chiffres</h2></center>
    <div class="counter_area">
        <div class="container">
            <div class="row">
                <div class="col-xl-4 col-md-4">
                    <div class="single_counter text-center">
                        <h3> <span class="counter" >1993</span>  </h3>
                        <span >Fondée en</span>
                    </div>
                </div>
                <div class="col-xl-4 col-md-4">
                    <div class="single_counter text-center">
                        <h3> <span>+</span><span class="counter" >600</span>  </h3>
                        <span>Client Satisfait</span>
                    </div>
                </div>
                <div class="col-xl-4 col-md-4">
                    
                    <div class="single_counter text-center">
                        <h3><span>+</span> <span class="counter" >500</span>  </h3>
                        <span>Projet Réalisé</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ counter  -->




     <!-- project  -->
     <div class="project_area">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="project_info text-center">
                        <h3>Vous avez une question ?</h3>

                        <a href="#" class="boxed-btn3-white">Contactez nous</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ project  -->
    {% endblock content %}

templates/blog-detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <!-- bradcam_area  -->
  <div class="bradcam_area breadcam_bg_4">
      <div class="container">
          <div class="row">
              <div class="col-xl-12">
                  <div class="bradcam_text text-center">
                      <h3>Single Blog</h3>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!--/ bradcam_area  -->

   <!--================Blog Area =================-->
   <section class="blog_area single-post-area section-padding">
      <div class="container">
         <div class="row">
            <div class="col-lg-8 posts-list">
               <div class="single-post">
                  <div class="feature-img">
                     <img class="img-fluid" src="{{post.image_1.url}}" alt="">
                  </div>
                  <div class="blog_details">
                     <h2>{{post.titre}}
                     </h2>
                     <ul class="blog-info-link mt-3 mb-4">
                        <li><a href="#"><i class="fa fa-user"></i> {{post.tag}}, {{post.created_date}}</a></li>
                     </ul>
                     <p class="excert">
                       {{post.intro}}
                     </p>
                     <p>
                       {{post.text_1}}
                     </p>
                     {% if post.image_2 %}
                       
                     <div class="feature-img">
                        <img class="img-fluid" src="{{post.image_2.url}}" alt="">
                     </div>
                     {% endif %}
                     {% if post.text_2 %}
                       
                     <p>
                        {{post.text_2}}
                     </p>
                     {% endif %}
                     {% if post.image_3 %}
                       
                     <div class="feature-img">
                        <img class="img-fluid" src="{{post.image_3.url}}" alt="">
                     </div>
                     {% endif %}
                     {% if post.text_3 %}
                       
                     <p>
                        {{post.text_3}}
                     </p>
                     {% endif %}


                  </div>
               </div>

            </div>
            <div class="col-lg-4">
               <div class="blog_right_sidebar">

                  <aside class="single_sidebar_widget popular_post_widget">
                     <h3 class="widget_title">Tous nos articles</h3>
                     {% for post in postes %}
                        <div class="media post_item">
                           <div class="media-body">
                              <a href="{% url 'post-detail' slug=post.slug %}">
                                 <h3>{{post.titre}}</h3>
                              </a>
                              <p>{{post.created_date}}</p>
                           </div>
                        </div>
                     {% endfor %}
                 </aside>
               </div>
            </div>
         </div>
      </div>
   </section>
   <!--================ Blog Area end =================-->

   {% block script %}
     
   <script>
      $('#datepicker').datepicker({
          iconsLibrary: 'fontawesome',
          icons: {
           rightIcon: '<span class="fa fa-caret-down"></span>'
       }
      });
      $('#datepicker2').datepicker({
          iconsLibrary: 'fontawesome',
          icons: {
           rightIcon: '<span class="fa fa-caret-down"></span>'
       }

      });
  </script>
   {% endblock script %}

   {% endblock content %}

templates/devis-form.html
<form id="test-form" action="#" method="POST" class="white-popup-block mfp-hide">
    {% csrf_token %}
    <div class="popup_box ">
        <div class="popup_inner">
            <div class="popup_header">
                <h3>Demandez un devis</h3>
            </div>
            <div class="custom_form">
                    <div class="row">
                        <div class="col-xl-12">
                            <input type="text" name="name" placeholder="Nom">
                        </div>
                        <div class="col-xl-12">
                            <input type="email" name="email" placeholder="Email">
                        </div>
                        <div class="col-xl-12">
                            <input type="text" name="phone" placeholder="Téléphone">
                        </div>
                        <div class="col-xl-12">
                            <textarea name="message" id="" cols="30" rows="10" placeholder="Message"></textarea>
                        </div>
                        <div class="col-xl-12">
                            <button type="submit" class="boxed-btn3">Envoyer</button>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</form>

templates/devis_form.html
<form id="test-form" action="#" method="POST" class="white-popup-block mfp-hide">
    {% csrf_token %}
    <div class="popup_box ">
        <div class="popup_inner">
            <div class="popup_header">
                <h3>Demandez un devis</h3>
            </div>
            <div class="custom_form">
                    <div class="row">
                        <div class="col-xl-12">
                            <input type="text" name="name" placeholder="Nom">
                        </div>
                        <div class="col-xl-12">
                            <input type="email" name="email" placeholder="Email">
                        </div>
                        <div class="col-xl-12">
                            <input type="text" name="phone" placeholder="Téléphone">
                        </div>
                        <div class="col-xl-12">
                            <textarea name="message" id="" cols="30" rows="10" placeholder="Message"></textarea>
                        </div>
                        <div class="col-xl-12">
                            <button type="submit" class="boxed-btn3">Envoyer</button>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</form>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  
    <!-- slider_area_start -->
    <div class="slider_area">
        <div class="slider_active owl-carousel">
            <div class="single_slider  d-flex align-items-center overlay2" style="background-image:url({% static 'img/banner/acc5.jpg' %});">
              {% comment %}
              {% endcomment %}
                <div class="container">
                    <div class="row d-flex justify-content-end">
                        <div class="col-xl-12">
                            <div class="slider_text ">
                                <!-- <h3> SUPELECTROTECH</h3> -->
                                <h3> La Sécurité En Toute Sérénité</h3>
                                <!-- <h4> Détection Intrusion</h4> -->
                                <div class="video_service_btn">
                                    
                                    <a href="{% url 'produits' %}" class="boxed-btn3-white"> <i class="fa fa-play"></i>
                                        Détection Intrusion</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="single_slider  d-flex align-items-center  overlay2" style="background-image:url({% static 'img/banner/acc1.jpg' %});">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="slider_text ">
                                <!-- <h3> SUPELECTROTECH</h3> -->
                                <h3> La Sécurité En Toute Sérénité </h3>
                                <!-- <h4>Détection Incendie Conventionnelle</h4> -->

                                <div class="video_service_btn">
                                    
                                    <a href="{% url 'produits' %}" class="boxed-btn3-white"> <i class="fa fa-play"></i>
                                        Détection Incendie Conventionnelle</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="single_slider  d-flex align-items-center  overlay2" style="background-image:url({% static 'img/banner/acc2.jpg' %});">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="slider_text ">
                                <!-- <h3> SUPELECTROTECH</h3> -->
                                <h3> La Sécurité En Toute Sérénité</h3>
                                
                                <div class="video_service_btn">
                                    
                                    <a href="{% url 'produits' %}" class="boxed-btn3-white"> <i class="fa fa-play"></i>Détection Incendie Adressable</a>
                                </div>
                                
                                <!-- <h4 cl>Détection Incendie Adressable</h4> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- slider_area_end -->

    <!-- service_area_start -->
    <!-- <div class="service_area">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="section_title text-center mb-50">
                        <h1>SUPELECTROTECH</h1>
                    </div>
                </div>
            </div>

        </div>
    </div> -->
    <!-- service_area_end -->

    <!-- about  -->
    <div class="about_area ">
        <div class="container-fluid p-0">
            <div class="row no-gutters align-items-center">
                <div class="col-xl-6 col-lg-6">
                    <div class="about_image">
                        <img src="{% static 'img/about/about.png' %}" alt="">
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6">
                    <div class="about_info">
                        <h3>SUPELECTROTECH, Toujours en Bonne Voie</h3>
                        <p>Fondée en 1993 et implantée à BLIDA, plus exactement à la Zone Industrielle ATLAS. SUPELECTROTECH n’est pas uniquement une entreprise d’Importation, et de Distribution des équipements de sécurité électronique ..</p>
                        <div class=" about_btn">
                            <a class="boxed-btn3" href="{% url 'about' %}#suite_about">En lire plus</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ about  -->






    <!-- gallery -->
    <div class="gallery_area">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                        <div class="section_title text-center mb-50">
                      
                                <h3>Nos produits populaires</h3>
                                <!-- <p>These cases are perfectly simple and easy to distinguish. In a free <br> hour, when our power of choice is untrammelled.</p> -->
                            </div>
                </div>
            </div>
            
            <div class="row grid">
                {% for  produit in popular  %}
                    <div class="col-xl-4 col-lg-6 grid-item cat1 col-md-6">
                        <div class="single-gallery mb-20">
                            <div class="portfolio-img">
                                    <img src="{{produit.photo.url}}" alt="">
                            </div>
                            <div class="gallery_hover">
                                <a  href="{% url 'produit-detail' slug=produit.slug %}" class="hover_inner">
                                    <h3>{{produit.reference}}</h3>
                                    <span>{{produit.get_category_display}}</span>
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}                 

            </div>
            <div class="row">
                <div class="col-xl-12">
                    <div class="More_Works_btn text-center">
                        <a class="boxed-btn3-green-2" href="{% url 'produits' %}">Plus de produits</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ gallery -->

    <!-- about wrap  -->
    <div class="about_wrap_area about_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-4 col-md-6 col-lg-4">
                    <div class="single_service_wrap text-center">
                        <img src="{% static 'img/svg_icon/puzzle.svg' %}" alt="">
                        <h3>Bon prix, Bon Choix</h3>
                    </div>
                </div>
                <div class="col-xl-4 col-md-6 col-lg-4">
                    <div class="single_service_wrap text-center">
                        <img src="{% static 'img/svg_icon/controls.svg' %}" alt="">
                        <h3>Qualité Garantie</h3>
                    </div>
                </div>
                <div class="col-xl-4 col-md-6 col-lg-4">
                    <div class="single_service_wrap text-center">
                        <img src="{% static 'img/svg_icon/bar-chart.svg' %}" alt="">
                        <h3>Accompagnement de A à Z</h3>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!--/ about wrap  -->






    <!-- project  -->
    <div class="project_area">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="project_info text-center">
                        <h3>Vous avez une question ?</h3>

                        <a href="{% url 'contact' %}" class="boxed-btn3-white">Contactez nous</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ project  -->
{% endblock content %}



<!-- <div class="row d-flex" style="display:flex">
    <div class="col-xl-4 col-md-4">
        <!-- <a href="{% url 'produits' %}#intrusion">
            <div class="single_service service_bg_1">
                <div class="service_hover">
                    
                </div>
            </div>
        </a> -->
        <!-- <h3>Détection Intrusion</h3>
        <h4 class=" mt-3">Gamme Complète et Innovante.</h4>
    </div>
    <div class="col-xl-4 col-md-4"> -->
        <!-- <a href="{% url 'produits' %}#conventionnelle">
            <div class="single_service service_bg_2">
                <div class="service_hover">
                    
                </div>
            </div>
        </a> -->
        <!-- <h3>Détection Incendie Conventionnelle</h3>
        <h4 class=" mt-3">Simple, Efficace et Facile à Installer</h4>
    </div>
    <div class="col-xl-4 col-md-4"> -->
        <!-- <a href="{% url 'contact' %}">
            <div class="single_service service_bg_3 hover_content">
                <div class="service_hover">
                    
                </div>
            </div>
        </a> -->
        <!-- <h3>Détection Incendie Adressable </h3>
        <h4 class=" mt-3">Technologie Pointue et Fiable</h4>

    </div>
</div> --> -->

templates/portfolio_details.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <div class="portfolio_details_area">
        <div class="container">
            <div class="row">
                <div class="col-xl-8 offset-xl-2">
                    <div class="portfolio_details_content text-center mb-50">
                        <span>Branding</span>
                        <h3>Gives you the best Financial  <br>
                            solution for business</h3>
                            <p>On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish.</p>
                    </div>
                </div>
                <div class="col-xl-12">
                    <div class="portfolio_details_thumb">
                        <img src="img/gallery/details_img_1.png" alt="">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-8 offset-xl-2">
                    <div class="portfolio_details_content mt-50 mb-50 text-center">
                        <h4>The Result</h4>
                            <p>On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish.</p>
                            <div class="live_view_btn mt-50">
                                <a href="#" class="boxed-btn3-green-2">Live View</a>
                            </div>
                    </div>
                </div>
                <div class="col-xl-12">
                    <div class="portfolio_details_thumb">
                        <img src="img/gallery/details_img_2.png" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    


    <!-- project  -->
    <div class="project_area">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="project_info text-center">
                        <h3>Do you Have any Project?</h3>
                        <p>Nam libero tempore, cum soluta nobis est eligendi optio <br>
                                cumque nihil impedit quo minus.</p>
                        <a href="#" class="boxed-btn3-white">Contact Us</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ project  -->
    {% endblock content %}